package com.williamspreitzer.craps.bets;

public enum BetType {

	ALL_BET,
	ANY_CRAPS_BET,
	ANY_SEVEN_BET,
	COME_BET,
	CRAPS_TWO_OR_TWELEVE_BET,
	DONT_COME_BAR_TWELEVE_BET,
	DONT_PASS_BAR_TWELEVE_BET,
	DOUBLES_BET,
	FIELD_BET,
	FIRE_BET,
	FIVE_NINE_PLACE_BET,
	FIVE_NINE_ODDS_BET,
	FOUR_TEN_HARDWAY_BET,
	FOUR_TEN_ODDS_BET,
	FOUR_TEN_PLACE_BET,
	FOUR_ROLLS_NO_SEVEN,
	HORN_BET,
	MIDWAY_BET,
	OVER_SEVEN_BET,
	PASS_LINE_BET,
	SIX_EIGHT_HARDWAY_BET,
	SIX_EIGHT_ODDS_BET,
	SIX_EIGHT_PLACE_BET,
	SMALL_BET,
	TALL_BET,
	THREE_OR_ELEVEN_BET,
	UNDER_SEVEN_BET,
	WORLD_BET
}